[package]
name = "tsp-blockchain-pow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
strum_macros = "0.24"
regex = "1"
rand = "0.8.4"
#bitcoin = "0.29.1"
sha2 = "0.10.6"